### ISSUE TITLE
No implementation found for method getPlatformVersion on channel plugins.flutter.zendesk_chat_api/calls

### ISSUE THREAD

**Issue by nilecrocodile** [ChangeFinance/zendesk-flutter-plugin#29] opened 2020-08-13 15:49 UTC
Didn't change anything, just added the dependency and copied the example and specified _zendeskAccountkey. And after starting the chat, I get this exception:

`E/flutter ( 2211): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel plugins.flutter.zendesk_chat_api/calls)
E/flutter ( 2211): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter ( 2211): <asynchronous suspension>`

**Comment by sudoFerraz** [comment] 2020-08-13 15:57
@nilecrocodile Can you please paste your flutter doctor -v
And also specify in which channel and version your flutter is?

**Comment by nilecrocodile** [comment] 2020-08-13 16:00
Thanks for the quick response. Here is the result doctor:

`[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.18363.1016], locale ru-RU)
    • Flutter version 1.20.0 at c:\Users\Dmitry\flutter
    • Framework revision 840c9205b3 (9 days ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.44.2)
    • VS Code at C:\Users\Dmitry\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories`

_And also specify in which channel and version your flutter is?_
Could you clarify how I can check this?

**Comment by sudoFerraz** [comment] 2020-08-13 16:05
@nilecrocodile Can you please try to move your flutter to version v1.9.1+hotfix.6 on channel stable and try to reproduce the same behavior?

**Comment by sudoFerraz** [comment] 2020-08-13 16:09
Please also try to change this file
https://github.com/onka13/zendesk-flutter-plugin/commit/e3d3a34d724011cb20c205e9ba958b0026052099

**Comment by nilecrocodile** [comment] 2020-08-14 10:39
I was unable to start the application on the version v1.9.1+hotfix.6. There were no errors in the console, but on the emulator and on a real smartphone, the application immediately closed. However, after returning to the stable flatter channel, I no longer get this error.

Please tell me, your plugin does not have a ready-made chat where user can enter messages? Because when I click on "Start Chat", the interface will not change, and I am unable to type a text message.

By the way, when I click on the "Start Chat" button, I get the message `W/cr_media( 8925): Requires BLUETOOTH permission`

which is eliminated by adding

```
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
```

to the _**example/android/app/src/main/AndroidManifest.xml**_

**Comment by nilecrocodile** [comment] 2020-08-14 10:47
I am sorry, it is not so. When I run your example I get it via git clone. Then I have no error. But when I integrate your plugin into my project as a dependency, I get this same error. But I cannot translate my project to another version of flutter because other packages stop working.

**Comment by nilecrocodile** [comment] 2020-08-14 11:12
> 
> 
> Please also try to change this file
> [onka13@e3d3a34](https://github.com/onka13/zendesk-flutter-plugin/commit/e3d3a34d724011cb20c205e9ba958b0026052099)

I found this file in the path C:\Users\...\flutter\.pub-cache\hosted\pub.dartlang.org\zendesk_flutter_plugin-1.0.2\android\src\main\java\com\getchange\zendesk_flutter_plugin\ZendeskFlutterPlugin.java

Applied these changes and it didn't help

**Comment by nilecrocodile** [comment] 2020-08-14 13:00
Experimentally, I found out that if you just copy the "main.dart" file from the example to my project, then this error occurs. However, if I also copy the entire Android folder, the problem disappears. Apparently the matter is in some settings for the gradle (or something else). Tell me what should I change in my Android folder to fix this error?

**Comment by lkettwig** [comment] 2020-08-19 20:28
I am having this same error on Android when I import the package.  Is there a resolution for this?

**Comment by sudoFerraz** [comment] 2020-09-01 11:49
@nilecrocodile Have you found a resolution?

**Comment by maurodibert** [comment] 2020-09-30 11:11
Hi, having same issue here. Is there any update? Thanks!

**Comment by sudoFerraz** [comment] 2020-09-30 11:58
@maurodibert Can you check the other resolutions on the closed issues? If it didn't solved your problem, please do a flutter doctor -v and paste the output here. It might be the flutter version you are using.

**Comment by maurodibert** [comment] 2020-09-30 13:57
@sudoFerraz hi! I was looking for the file you mention but I don't have that in my project, a starter project directly created with VSCode. I also try to follow indications on Fragments and that stuff but I'm not sure how to proceed... Sorry if I'm bothering with this but I need to implement a chat and your package seems super complete and easy to implement.

This is my flutter doctor:

✓] Flutter (Channel stable, 1.20.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.4 at /home/maurodibert/Documents/Coding/Ingenious/flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/maurodibert/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by sudoFerraz** [comment] 2020-09-30 14:37
@maurodibert Your flutter version seems correct, please do a flutter clean and delete your /hosted inside of the .pubcache on your home directory. After this run a flutter pub get on the directory of your project and make sure that no previous install on the emulator or device you are using are present. 

If this still does not solve please try the following solution by editing and adding this line on your android GeneratedPluginRegistrant, like this:

import io.flutter.flutter.zendesk_chat_api;

ConnectivityPlugin.registerWith(registry.registrarFor("io.flutter.plugins.flutter.zendesk_chat_api"));

Please also paste the exact error you are seeing when trying to do flutter run

**Comment by maurodibert** [comment] 2020-09-30 19:39
@sudoFerraz I've tried everything you've suggested but it still fails. Here it is my error (thanks again!):

E/flutter (28701): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel plugins.flutter.zendesk_chat_api/calls)
E/flutter (28701): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (28701): <asynchronous suspension>
E/flutter (28701): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (28701): #2      ZendeskFlutterPlugin.platformVersion (package:zendesk_flutter_plugin/zendesk_flutter_plugin.dart:38:29)
E/flutter (28701): #3      _ChatViewState.initPlatformState (package:miki/screens/views/chat_view.dart:38:40)
E/flutter (28701): #4      _ChatViewState.initState (package:miki/screens/views/chat_view.dart:30:5)
E/flutter (28701): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
E/flutter (28701): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (28701): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (28701): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
E/flutter (28701): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (28701): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (28701): #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
E/flutter (28701): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (28701): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (28701): #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
E/flutter (28701): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (28701): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (28701): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
E/flutter (28701): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #21     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5566:32)
E/flutter (28701): #22     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
E/flutter (28701): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (28701): #25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (28701): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (28701): #27     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
E/flutter (28701): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (28701): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (28701): #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
E/flutter (28701): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (28701): #34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (28701): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (28701): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
E/flutter (28701): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
E/flutter (28701): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (28701): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (28701): #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
E/flutter (28701): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (28701): #44     SingleChildRenderObjectElement.update (package:flutter/s

**Comment by sudoFerraz** [comment] 2020-10-01 11:39
@maurodibert Can you please clone the project and pull the latest changes and then switch to the flutter version v1.9.1+hotfix.6, let's see what we get, when you try to run the example application only

**Comment by sudoFerraz** [comment] 2020-10-05 14:51
Closing this as no updates were given, will be happy to reopen it if anyone has an update, please let us know if there is any resolution to this

**Closed by sudoFerraz** 2020-10-05 14:51 UTC
Labels: bug

**Comment by fhsbatista** [comment] 2020-12-18 23:34
I'm facing the same problem here... isn't the problem the fact that MainActivity.java doesn't register the ZendeskFlutterPlugin? I was testing a few things a searching for the errors I'm facing and it looks that problem of this issue here is likely due to the fact that mainactivity doesn't register the plugin
